# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  clean-up-sikkim
Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs22.x
    Timeout: 10
    MemorySize: 128
    Environment:
      Variables:
        DYNAMODB_ENDPOINT: http://host.docker.internal:8000

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: "The deployment environment."

Resources:
  Users:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: city
          AttributeType: S
        - AttributeName: state
          AttributeType: S
        - AttributeName: totalPoints
          AttributeType: N
        - AttributeName: leaderboardPartition
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: GSI-City-Points
          KeySchema:
            - AttributeName: city
              KeyType: HASH
            - AttributeName: totalPoints
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: GSI-State-Points
          KeySchema:
            - AttributeName: state
              KeyType: HASH
            - AttributeName: totalPoints
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: GSI-NationalLeaderboard
          KeySchema:
            - AttributeName: leaderboardPartition
              KeyType: HASH
            - AttributeName: totalPoints
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  DumpPins:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DumpPins
      AttributeDefinitions:
        - AttributeName: pinId
          AttributeType: S
        - AttributeName: geohash
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: city
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: state
          AttributeType: S
        - AttributeName: reportedBy
          AttributeType: S
      KeySchema:
        - AttributeName: pinId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: GSI-Geohash
          KeySchema:
            - AttributeName: geohash
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: GSI-City-Status
          KeySchema:
            - AttributeName: city
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: GSI-State-Status
          KeySchema:
            - AttributeName: state
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: GSI-ReportedBy
          KeySchema:
            - AttributeName: reportedBy
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  Events:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Events
      AttributeDefinitions:
        - AttributeName: eventId
          AttributeType: S
        - AttributeName: pinId
          AttributeType: S
        - AttributeName: scheduledAt
          AttributeType: S
        - AttributeName: city
          AttributeType: S
        - AttributeName: state
          AttributeType: S
        - AttributeName: organisedBy
          AttributeType: S
      KeySchema:
        - AttributeName: eventId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: GSI-Pin-Events
          KeySchema:
            - AttributeName: pinId
              KeyType: HASH
            - AttributeName: scheduledAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: GSI-City-Events
          KeySchema:
            - AttributeName: city
              KeyType: HASH
            - AttributeName: scheduledAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: GSI-State-Events
          KeySchema:
            - AttributeName: state
              KeyType: HASH
            - AttributeName: scheduledAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: GSI-OrganizerEvents
          KeySchema:
            - AttributeName: organisedBy
              KeyType: HASH
            - AttributeName: scheduledAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  EventParticipants:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: EventParticipants
      AttributeDefinitions:
        - AttributeName: eventId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: registeredAt
          AttributeType: S
      KeySchema:
        - AttributeName: eventId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI-UserEvents
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: registeredAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  PointTransactions:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PointTransactions
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: txnId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: txnId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  Badges:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Badges
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: badgeId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: badgeId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  getTrashDumps:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get-trash-dumps.getTrashDumpsHandler
      CodeUri: src/handlers/trash-dump-pins
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Get all trash dump pins for a given lat and lng.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /trash-dumps
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - get-trash-dumps.ts

  createTrashDumpPin:
    Type: AWS::Serverless::Function
    Properties:
      Handler: create-trash-dump-pin.createTrashDumpPinHandler
      CodeUri: src/handlers/trash-dump-pins
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Create a new trash dump pin with given details.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /trash-dumps
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - create-trash-dump-pin.ts

  deleteTrashDumpPin:
    Type: AWS::Serverless::Function
    Properties:
      Handler: delete-trash-dump-pin.deleteTrashDumpPinHandler
      CodeUri: src/handlers/trash-dump-pins
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Delete trash dump pin handler.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /trash-dumps
            Method: DELETE
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - delete-trash-dump-pin.ts

  updateTrashDumpPinStatus:
    Type: AWS::Serverless::Function
    Properties:
      Handler: update-trash-dump-pin-status.updateTrashDumpPinStatusHandler
      CodeUri: src/handlers/trash-dump-pins
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Update trash dump pin status - OPEN, CLOSED, .
      Events:
        Api:
          Type: Api
          Properties:
            Path: /trash-dumps
            Method: PATCH
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - update-trash-dump-pin-status.ts

  createUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: create-user.createUserHandler
      CodeUri: src/handlers/user
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 10
      Description: Create a new user in the Users table.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /users
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - create-user.ts

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"

  UsersTableName:
    Value: !Ref Users
    Export:
      Name: !Sub "${Environment}-SwachhMap-UsersTable"

  UsersTableArn:
    Value: !GetAtt Users.Arn
    Export:
      Name: !Sub "${Environment}-SwachhMap-UsersTableArn"

  DumpPinsTableName:
    Value: !Ref DumpPins
    Export:
      Name: !Sub "${Environment}-SwachhMap-DumpPinsTable"

  DumpPinsTableArn:
    Value: !GetAtt DumpPins.Arn
    Export:
      Name: !Sub "${Environment}-SwachhMap-DumpPinsTableArn"

  EventsTableName:
    Value: !Ref Events
    Export:
      Name: !Sub "${Environment}-SwachhMap-EventsTable"

  EventsTableArn:
    Value: !GetAtt Events.Arn
    Export:
      Name: !Sub "${Environment}-SwachhMap-EventsTableArn"

  EventParticipantsTableName:
    Value: !Ref EventParticipants
    Export:
      Name: !Sub "${Environment}-SwachhMap-EventParticipantsTable"

  EventParticipantsTableArn:
    Value: !GetAtt EventParticipants.Arn
    Export:
      Name: !Sub "${Environment}-SwachhMap-EventParticipantsTableArn"

  PointTransactionsTableName:
    Value: !Ref PointTransactions
    Export:
      Name: !Sub "${Environment}-SwachhMap-PointTransactionsTable"

  PointTransactionsTableArn:
    Value: !GetAtt PointTransactions.Arn
    Export:
      Name: !Sub "${Environment}-SwachhMap-PointTransactionsTableArn"

  BadgesTableName:
    Value: !Ref Badges
    Export:
      Name: !Sub "${Environment}-SwachhMap-BadgesTable"

  BadgesTableArn:
    Value: !GetAtt Badges.Arn
    Export:
      Name: !Sub "${Environment}-SwachhMap-BadgesTableArn"
