# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  clean-up-sikkim
Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs22.x
    Timeout: 10
    MemorySize: 128
    Environment:
      Variables:
        MAIN_TABLE: !Ref MainTable
        NOTIFICATIONS_TABLE_NAME: !Ref UserNotificationsTable
        DYNAMODB_ENDPOINT: http://host.docker.internal:8000

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: "The deployment environment."

Resources:
  MainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "clean-up-app-main-${Environment}"
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S

      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  UserNotificationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub clean-up-app-notifications-${Environment}
      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S

      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  getFruits:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-fruits.getFruitsHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get all fruits from a DynamoDB table.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /fruits
            Method: GET

  getTrashDumps:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-trash-dumps.getTrashDumpsHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get all trash dumps from a DynamoDB table.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /trash-dumps
            Method: GET

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"
